Added custom tasks and custom manifests

diff --git a/run b/run
--- a/run
+++ b/run
@@ -2,45 +2,46 @@
 
 function main()
 {
-	# only show output on fail
-	# NOISY=${NOISY:-false}
-	# if [[ $NOISY = true ]]; then
-	# 	# set -eo pipefail
-	# fi
-
 	# load app
-	local from=${TASKS_PATH:-"$PWD"}
-	source "$from/src/helpers.sh"
-	source "$from/src/ssh.sh"
+	export TASKS_PATH=${TASKS_PATH:-"$PWD"}
+	source "$TASKS_PATH/src/helpers.sh"
+	source "$TASKS_PATH/src/ssh.sh"
+	source "$TASKS_PATH/src/load_task.sh"
 
 	# colours
 	_set_colours
 
-	# loads task
+	# get task name and remove from $@
 	local task=${1:-"help"}; shift
-	source "$from/src/tasks/$task.sh"
 
-	# server manifest
-	local manifest=${MANIFEST:-"$from/manifest"}
-	servers=${1:-''}
-	_is_file $manifest && _is_empty $servers && read -a servers <<< $(cat $manifest)
+	# find manifest
+	local manifest=${1:-""}
+	local servers
+	_is_empty $manifest && manifest=${TASKS_MANIFEST:-"$TASKS_PATH/manifest"} # use default manifests if none was provided
+	_is_file $manifest && read -a servers <<< $(cat $manifest) # load manifest into array
 
-	# declare runner
+	# no manifest found
+	_is_not_file $manifest && echo "${red}ERROR${reset} You're missing a manifest file. See the readme for help." && exit 1
+
+	# set runner as an array from servers
 	_is_array servers && runner=("${servers[@]}")
 	_is_not_array servers && runner[0]=$servers
 
+	# load task
+	_load_task $task $runner "$@"
+
 	# run task
-	ASYNC=${ASYNC:-false}
+	local background=${TASKS_BACKGROUND:-false}
 	for run in "${runner[@]}"; do
 		echo "${yellow}--->${green} $run ${blue}$task${reset}"
 
 		# run in foreground
-		[ $ASYNC = false ] && _task $run "$@"
+		[ $background = false ] && _task $run "$@"
 
 		# run in background
-		[ $ASYNC = true ] && _task $run "$@" &
-		[ $ASYNC = true ] && echo '	running in background'
+		[ $background = true ] && _task $run "$@" &
+		[ $background = true ] && echo '    running in background'
 	done
 }
 
-main $@
+main "$@"
